### ISSUE TITLE
Incompatible with ServerCore mod, crashes on launch

### ISSUE THREAD

**Issue by omash03** [RelativityMC/VMP-fabric#1]
Using VMP version 1.18.1-pre1-0.2.0+beta1.2
ServerCore version 1.2.5 1.18

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/5/21, 12:40 AM
Description: Exception ticking world

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_6540 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3215.method_14161(class_3215.java:352)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:305)
	at net.minecraft.server.MinecraftServer.redirect$znh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3750)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zgh000$modifiedRunLoop(MinecraftServer.java:2856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [servercore.mixins.json:optimizations.mob_spawning.LocalMobCapCalculatorMixin] from phase [DEFAULT] in config [servercore.mixins.json] from mod [servercore-fabric] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_6540::useDistanceMap$1 with priority 1000 cannot inject into net/minecraft/class_6540::method_38084(Lnet/minecraft/class_1311;Lnet/minecraft/class_1923;)Z merged by com.ishland.vmp.mixins.playerwatching.optimize_nearby_player_lookups.MixinSpawnDensityCapper with priority 1050 [PREINJECT Applicator Phase -> servercore.mixins.json:optimizations.mob_spawning.LocalMobCapCalculatorMixin -> Prepare Injections ->  -> redirect$bnm000$useDistanceMap$1(Ljava/util/List;Lnet/minecraft/class_1311;Lnet/minecraft/class_1923;)Ljava/util/Iterator; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3215.method_14161(class_3215.java:352)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:305)
	at net.minecraft.server.MinecraftServer.redirect$znh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3750)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (1191,64,-176), Section: (at 7,0,0 in 74,4,-11; chunk contains blocks 1184,-64,-176 to 1199,319,-161), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
	Level time: 5213254 game time, 5357821 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 93220 (now: false), thunder time: 132109 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zgh000$modifiedRunLoop(MinecraftServer.java:2856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Linux (aarch64) version 5.11.0-1022-oracle
	Java Version: 17, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 4905746776 bytes (4678 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 4
	Graphics card #0 name: Virtio GPU
	Graphics card #0 vendor: Red Hat, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: version: 01
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MB): 8064.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: RAM
	Virtual memory max (MB): 7440.43
	Virtual memory used (MB): 9673.18
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 11 total; -Xms8G -Xmx8G -XX:+UseLargePages -XX:LargePageSizeInBytes=2M -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:+DisableExplicitGC
	Fabric Mods: 
		antixray: AntiXray 1.1.2
		axesareweapons: Axes Are Weapons 1.5.1
		blue_endless_jankson: jankson 1.2.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.96
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.43
		collective-fabric: Collective (Fabric) 3.9
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		elativitymc_c2me-fabric_ver_1_18_libs_: libs 0.2.0+alpha.5.96
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.8
		fiber: fiber 0.23.0-2
		java: OpenJDK 64-Bit Server VM 17
		kyrptconfig: Kyrpt Config 1.2.4-1.18
		lithium: Lithium 0.7.6-SNAPSHOT
		minecraft: Minecraft 1.18
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player-data-api: Player Data API 0.1.0+1.18
		recipecache: recipecache 0.2.1-1.17.1
		servercore-fabric: ServerCore-Fabric 1.2.5-1.18
		starlight: Starlight 1.0.0+fabric.5e8a60d
		styledplayerlist: Styled Player List 2.1.3+1.18
		treeharvester-fabric: Tree Harvester (Fabric) 4.1
		vmp: Very Many Players 0.2.0+beta.1.2
	Server Running: true
	Player Count: 0 / 15; []
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by omash03** [comment]
This issue has been resolved
https://github.com/Wesley1808/ServerCore-Fabric/commit/484023091304ac79dbdded54378b1ab5285e083e
