### ISSUE TITLE
Crash on player join (Exception ticking world) 

### ISSUE THREAD

**Issue by Azarattum** [RelativityMC/VMP-fabric#25]
**Describe the bug**
Server crashes when a player joins.

**To Reproduce**
1. Join a server

**Expected behavior**
Should not crash.

**Runtime info (please complete the following information):**
 - OS: Linux cont10804 2.6.32-042stab145.3
 - Minecraft version: 1.19.2
 - Mod version: vmp-fabric-mc1.19.2-0.2.0+beta.7.0-all.jar

**Crash reports / logs**
```
[17:29:40] [Server thread/INFO]: Azarattum joined the game
[17:29:40] [Netty Epoll Play IO Thread #0/INFO]: [STDOUT]: VMP: Started priority handler
[17:29:43] [Server thread/INFO]: Async chunk loading for player Azarattum completed
[17:29:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbg000$modifiedRunLoop(MinecraftServer.java:3385) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3204$class_4077.method_14027(long, int, boolean)" because "this.field_18252" is null
        at net.minecraft.class_3204.handler$bim000$purge(class_3204.java:2621) ~[server-intermediary.jar:?]
        at net.minecraft.class_3204.method_14045(class_3204.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:319) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:319) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$bbo000$catchExceptions(MinecraftServer.java:5282) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
        ... 6 more
[17:29:44] [Server thread/ERROR]: This crash report has been saved to: /home/epicness/./crash-reports/crash-2022-09-30_17.29.44-server.txt
[17:29:44] [Thread-460/INFO]: Voice UDP server stopped
[17:29:44] [Server thread/INFO]: Stopping server
[17:29:44] [Server thread/INFO]: Saving players
[17:29:44] [Server thread/INFO]: Azarattum lost connection: Server closed
[17:29:44] [Server thread/INFO]: Azarattum left the game
[17:29:44] [Server thread/INFO]: Saving worlds
[17:29:44] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3204$class_4077.method_14027(long, int, boolean)" because "this.field_18252" is null
        at net.minecraft.class_3204.handler$bim000$purge(class_3204.java:2621) ~[server-intermediary.jar:?]
        at net.minecraft.class_3204.method_14045(class_3204.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:319) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:587) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
[17:30:44] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[17:30:44] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[17:30:44] [Server Watchdog/ERROR]: This crash report has been saved to: /home/epicness/./crash-reports/crash-2022-09-30_17.30.44-server.txt
```

**Other mods**
```
Alternate Current                             Modrinth   r0v8vy1s
Cardinal Components API                       Modrinth   K01OU20C
Carpet                                        CurseForge 349239
Carpet Extra                                  CurseForge 349240
Carpet-Fixes                                  CurseForge 529720
EasyAuth                                      Modrinth   aZj58GfX
Fabric API                                    Modrinth   P7dR8mSH
Fabric Language Kotlin                        Modrinth   Ha28R6CL
Fabric Tailor                                 Modrinth   g8w1NapE
FerriteCore                                   Modrinth   uXXizFIs
Krypton                                       Modrinth   fQEb0iXm
Lithium                                       Modrinth   gvQqBUqZ
Memory Leak Fix                               Modrinth   NRjRiSSD
No Chat Reports                               Modrinth   qQyHxfxd
Plasmo Voice                                  Modrinth   1bZhdhsH
ServerCore                                    Modrinth   4WWQxlQP
Servux                                        CurseForge 406323
Simple Discord Link                           Modrinth   Sh0YauEf
Starlight (Fabric)                            Modrinth   H8CaAYZC
Very Many Players (Fabric)                    Modrinth   wnEe9KBa
```

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
Try reproduce without carpet-fixes.

**Comment by Azarattum** [comment]
@ishland you are right. It works fine with `carpet-fixes` disabled.

carpet-fixes.conf:
```
optimizedHypot true
optimizedRounding true
optimizedPoweredRails true
optimizedTicketManager true
optimizedBiomeAccess true
optimizedNeighborUpdater true
optimizedRecipeManager true
```

**Comment by ishland** [comment]
I would suspect `optimizedTicketManager` as it caused a similar crash before.

**Comment by Azarattum** [comment]
Disabling `optimizedTicketManager` fixes the issue, indeed.

What would you suggest optimization-wise is better VMP or carpet-fixes with `optimizedTicketManager`? My server doesn't have that Many Players. Is there any benefit in running VPM on low player (<7) servers at all?

**Comment by ishland** [comment]
VMP contains a better version of `optimizedTicketManager` along with many other micro-optimizations. It will still reduce mspt slightly on entity-heavy scenarios on lower playercounts.

**Comment by pokesmells** [comment]
https://pastebin.com/i0LYM4Vt - Crash log
https://pastebin.com/b8uZT2mE - List of Mods

**Comment by pokesmells** [comment]
I've been having consistent crashes with VMP, I have no clear idea as to what's causing it, but in terms of the stuff above, I do have a similar mod called "Debugify" which implements some fixes

**Comment by pokesmells** [comment]
After doing some testing, I have experienced no crashes so far with VMP disabled,

**Comment by ishland** [comment]
@Poke097 Please try getting the minimum list of mods reproducible and open a new issue.

**Comment by ishland** [comment]
Closing as resolved.
