### ISSUE TITLE
Lag when it comes to breaking blocks 1.19.2

### ISSUE THREAD

**Issue by papillo12** [RelativityMC/VMP-fabric#32]
**Describe the bug**
Lag when breaking blocks, it's like the ghost block problem and I know I have no lag

**To Reproduce**
1. install the mod in the server with the modpack that I have
2. break blocks to see if the error happens

**Expected behavior**

**Screenshots**
breaking blocks without VMP: https://streamable.com/ej4nq6
breaking blocks with VMP: https://streamable.com/pnl1rl

**Runtime info (please complete the following information):**
 - OS:  windows 11
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0+beta.7.11+1.19.2
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
[latest (1).log](https://github.com/RelativityMC/VMP-fabric/files/9966053/latest.1.log)

**Other mods**

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by IAmSneak** [comment]
I experience the same issue. The mods we have in common are: cloth api, cloth config, fabric language kotlin, fabric api, ferritecore, krypton, lazydfu, lithium, memoryleakfix, nochatreports, spark, and vmp.

Not sure if this is related but after i /stop'ed the server it gave this in the logs. It did not give that error when stopping the server before the issue started occurring (it only occurs after a while and a few players have joined).
``[22:01:09] [Netty Play IO Thread #17/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelException: java.net.SocketException: Socket is closed
	at io.netty.channel.socket.DefaultSocketChannelConfig.setSendBufferSize(DefaultSocketChannelConfig.java:231) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.setSendBufferSize(NioSocketChannel.java:488) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.setSendBufferSize(NioSocketChannel.java:474) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.socket.DefaultSocketChannelConfig.setOption(DefaultSocketChannelConfig.java:106) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.setOption(NioSocketChannel.java:498) ~[netty-transport-4.1.77.Final.jar:?]
	at com.ishland.vmp.common.networking.priority.PacketPriorityHandler.adjustSendBuffer(PacketPriorityHandler.java:425) ~[vmp-fabric-mc1.19.2-0.2.0+beta.7.15-all.jar:?]
	at com.ishland.vmp.common.networking.priority.PacketPriorityHandler.channelWritabilityChanged(PacketPriorityHandler.java:494) ~[vmp-fabric-mc1.19.2-0.2.0+beta.7.15-all.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:421) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1433) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:931) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:628) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:594) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:196) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:273) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:438) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:361) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:716) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.SocketException: Socket is closed
	at sun.nio.ch.Net.translateToSocketException(Net.java:179) ~[?:?]
	at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:249) ~[?:?]
	at sun.nio.ch.SocketAdaptor.setSendBufferSize(SocketAdaptor.java:331) ~[?:?]
	at io.netty.channel.socket.DefaultSocketChannelConfig.setSendBufferSize(DefaultSocketChannelConfig.java:229) ~[netty-transport-4.1.77.Final.jar:?]
	... 29 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:264) ~[?:?]
	at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:247) ~[?:?]
	at sun.nio.ch.SocketAdaptor.setSendBufferSize(SocketAdaptor.java:331) ~[?:?]
	at io.netty.channel.socket.DefaultSocketChannelConfig.setSendBufferSize(DefaultSocketChannelConfig.java:229) ~[netty-transport-4.1.77.Final.jar:?]
	... 29 more``

**Comment by pulpan977** [comment]
It's reproducible even without other client/server mods. Setting `use_packet_priority_system` to `false` resolves it for me.

**Comment by ishland** [comment]
This feature is now put back to experimental state and is now disabled by default.
